// This runner is auto-generated by Brittle

runTests()
Error.stackTraceLimit = Infinity
async function runTests () {
  const test = (await import('brittle')).default

  test.pause()

  await import('./index.test.js')

  test.resume()
}
